# Generated by Django 4.1.1 on 2022-09-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.FilePathField(path='/home/images', recursive=True)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
