# Generated by Django 4.1.1 on 2022-09-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(verbose_name='date captured'),
        ),
    ]
