# Generated by Django 4.1.1 on 2022-09-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoDB', '0002_alter_photo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='location',
            field=models.ImageField(upload_to=''),
        ),
    ]
