# Generated by Django 4.1.1 on 2022-09-21 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoDB', '0003_alter_photo_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='photo',
            new_name='photo_old',
        ),
    ]
